---
- name: Configure Postfix Gmail Relay
  hosts: server_prod
  become: yes
  gather_facts: no

  vars:
    sasl_file: /etc/postfix/sasl_passwd

  tasks:

    - name: Ensure postfix is installed
      ansible.builtin.package:
        name: postfix
        state: present

    - name: Configure sasl_passwd
      ansible.builtin.copy:
        dest: "{{ sasl_file }}"
        content: |
          [smtp.gmail.com]:587 {{ aji.panca@indodanafintech.co.id }}:{{ sbra jmpw bmby zwbo }}
        owner: root
        group: root
        mode: '0600'

    - name: Generate hash db file
      ansible.builtin.command:
        cmd: postmap hash:{{ sasl_file }}

    - name: Ensure main.cf relayhost configured
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^relayhost ='
        line: 'relayhost = [smtp.gmail.com]:587'

    - name: Enable SASL authentication
      ansible.builtin.blockinfile:
        path: /etc/postfix/main.cf
        block: |
          smtp_sasl_auth_enable = yes
          smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
          smtp_sasl_security_options = noanonymous
          smtp_tls_security_level = encrypt
          smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

    - name: Restart postfix
      ansible.builtin.service:
        name: postfix
        state: restarted
        enabled: yes

    - name: Flush mail queue
      ansible.builtin.command:
        cmd: postfix flush

    - name: Send test email
      ansible.builtin.shell: |
        echo -e "This is a test email.\nSent from server: $(hostname)" \
        | mail -s "SMTP Test from $(hostname)" {{ it.proxmox@indodanafintech.co.id }}
      args:
        executable: /bin/bash
