---
- name: Create user alice with root privileges (raw)
  hosts: all
  gather_facts: no
  become: true

  tasks:
    - name: Create user alice
      ansible.builtin.raw: |
        id alice &>/dev/null || \
        useradd -m -s /bin/bash alice && \
        echo "alice:password123" | chpasswd

    - name: Add alice to sudoers
      ansible.builtin.raw: |
        usermod -aG sudo alice
