- name: Create alice with password and sudo
  hosts: server
  gather_facts: true
  become: true

  tasks:
    - user:
        name: made
        password: "{{ 'password123' | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes

    - user:
        name: made
        groups: sudo
        append: yes
