- name: Create alice with password and sudo
  hosts: all
  become: true

  tasks:
    - name: Create user alice
      ansible.builtin.user:
        name: alice
        password: "{{ 'password123' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Add alice to sudo
      ansible.builtin.user:
        name: alice
        groups: sudo
        append: yes
