---
- name: Create user alice with sudo privileges (raw)
  hosts: all
  gather_facts: no
  become: true

  tasks:
    - name: Create user alice
      ansible.builtin.raw: |
        id alice &>/dev/null || useradd -m -s /bin/bash alice

    - name: Set password for alice
      ansible.builtin.raw: |
        echo "alice:password123" | sudo chpasswd

    - name: Add alice to sudo group
      ansible.builtin.raw: |
        usermod -aG sudo alice
