---
- name: Update and upgrade APT without Python
  hosts: all
  become: true

  tasks:
    - name: Update APT cache
      ansible.builtin.raw: apt update -y

    - name: Upgrade all packages
      ansible.builtin.raw: apt upgrade -y
